//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entityframework_CURD
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<int> deptid { get; set; }
        public Nullable<int> sts { get; set; }
    
        public virtual department department { get; set; }
    }
}
