//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string fname { get; set; }
        public string mname { get; set; }
        public string lname { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string dated { get; set; }
        public int ID { get; set; }
    }
}
